const NAVIGATOR_LANGUAGE = navigator.language.toLowerCase();
const ENGLISH_CONTEXT_MENU_ID = "en-us";
const PORTUGUESE_CONTEXT_MENU_ID = "pt-br";

const CONTEXT_MENU_IDS = [
    ENGLISH_CONTEXT_MENU_ID,
    PORTUGUESE_CONTEXT_MENU_ID
];

export {
    NAVIGATOR_LANGUAGE,
    CONTEXT_MENU_IDS,
    ENGLISH_CONTEXT_MENU_ID,
    PORTUGUESE_CONTEXT_MENU_ID
};